services:
  mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
      - 'MYSQL_DATABASE=${DATABASE}'
      - 'MYSQL_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD}'
      - 'MYSQL_USER=${DB_USERNAME}'
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - task-net

  task-app:
    container_name: task-management-app
    build: .
    image: task-management-api:v1.0.0
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - task-net

volumes:
  mysql_data:

networks:
  task-net:
    driver: bridge