name: Task Management CI

on:
  push:
    branches: [ 'main', 'features/*']
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  code-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run spotbugs check
        run: mvn clean validate spotbugs:check -Dspotbugs.report.format=xml -Dspotbugs.report.filename=target/reports/spotbugs.xml

      - name: Run PMD check
        run: mvn validate pmd:check -Dpmd.reportFormat=xml -Dpmd.outputFile=target/reports/pmd.xml

      - name: Upload PMD report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pmd-report
          path: target/reports/pmd.xml

      - name: Upload Spotbugs report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: spotbugs-report
          path: target/reports/spotbugs.xml

  build-and-run-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: wait for mysql to be ready
        run: |
          for i in {30..0}; do
            if docker exec mysql mysql -u $MYSQL_USER -p $MYSQL_PASSWORD -e 'SELECT 1' $MYSQL_DATABASE; then
              echo "MySQL is up and running"
              break
            fi
            echo 'Waiting for MySQL...'
            sleep 1
          done

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependency
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Build and run tests with coverage
        run: mvn clean install jacoco:report -Djacoco.failOnViolation=true -Djacoco.coverageThreshold=0.8

      - name: Upload jacoco coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html
